version: "3"
services:
  app:
    build:
      args:
        user: development
        uid: 9999
      context: ./
      dockerfile: Dockerfile
    image: sample:latest
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./:/var/www
    networks:
      - sample-network
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: genpass
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: genpass
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - /var/lib/mysql
    networks:
      - sample-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    links:
      - db:db
    ports:
      - "127.0.0.1:8001:80"
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: genpass
      MYSQL_ROOT_PASSWORD: genpass
      UPLOAD_LIMIT: 100M
    networks:
      - sample-network
  nginx:
    image: nginx:1.23.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sample-network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "127.0.0.1:1025:1025" # smtp server
      - "127.0.0.1:8025:8025" # web ui
    networks:
      - sample-network
networks:
  sample-network:
    driver: bridge
    attachable: true
